name: 'Add terraform plan comment'
description: 'add a terraform plan comment'

inputs:
  token:
    description: 'token'
    required: false
    default: ${{ github.token }}
  repository:
    description: 'repository'
    required: false
    default: ${{ github.repository }}
  issue-number:
    description: 'issue-number'
    required: true
    default: ''
  directory:
    description: 'directory'
    required: true
    default: ''
  stdout:
    description: 'terraform plan outputs.stdout'
    required: true
    default: ''
  stderr:
    description: 'terraform plan outputs.stderr'
    required: true
    default: ''

runs:
  using: 'node16'
  main: 'dist/index.js'
