name: 'Add terraform plan comment'
description: 'add a terraform plan comment'

inputs:
  issue-number:
    description: 'issue-number'
    required: true
    default: ''
  token:
    description: 'token'
    required: true
    default: ''
  directory:
    description: 'directory'
    required: true
    default: ''
  stdout:
    description: 'terraform plan outputs.stdout'
    required: true
    default: ''
  stderr:
    description: 'terraform plan outputs.stderr'
    required: true
    default: ''

runs:
  using: 'node16'
  main: 'dist/index.js'
